# Generated by Django 2.1 on 2018-08-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledges_entered_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='imgs/%Y/%m/%d')),
                ('file', models.FileField(blank=True, upload_to='imgs/%Y/%m/%d')),
                ('embed_code', models.TextField(blank=True, default='')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledge_contents', to='knowledge.Knowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
