# Generated by Django 2.1 on 2018-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name_plural': '1. Knowledge'},
        ),
        migrations.AlterModelOptions(
            name='knowledgecontent',
            options={'verbose_name_plural': '2. Knowledge Content'},
        ),
    ]
