# Generated by Django 2.1 on 2018-09-08 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges_entered_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgecontent',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_contents', to='knowledge.Knowledge'),
        ),
    ]
