# Generated by Django 2.1 on 2019-08-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('knowledge', '0004_auto_20180907_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_knowledge', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_knowledge', to='categories.SubCategory'),
        ),
    ]
