# Generated by Django 2.1 on 2019-10-21 08:22

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
        ('practice', '0034_practicesession_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Money Benefit')),
            ],
            options={
                'verbose_name': 'Money Benefit',
                'verbose_name_plural': 'Money Benefits',
            },
        ),
        migrations.CreateModel(
            name='PeopleBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='People Benefit')),
            ],
            options={
                'verbose_name': 'People Benefit',
                'verbose_name_plural': 'People Benefits',
            },
        ),
        migrations.CreateModel(
            name='SelfBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Self Benefit')),
            ],
            options={
                'verbose_name': 'Self Benefit',
                'verbose_name_plural': 'Self Benefits',
            },
        ),
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Want')),
                ('first_positive_belief', models.TextField(verbose_name='First Positive Belief')),
                ('second_positive_belief', models.TextField(verbose_name='Second Positive Belief')),
                ('third_positive_belief', models.TextField(verbose_name='Third Positive Belief')),
                ('want_instruction_video', models.CharField(max_length=250, verbose_name='Want Instruction Video')),
                ('tasks_instruction_video', models.CharField(max_length=250, verbose_name='Tasks Instruction Video')),
                ('beliefs_instruction_video', models.CharField(max_length=250, verbose_name='Positive Beliefs Instruction Video')),
                ('ability_instruction_video', models.CharField(max_length=250, verbose_name='Abilities Instruction Video')),
                ('ps_instruction_video', models.CharField(max_length=250, verbose_name='Practice Sessions Instruction Video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_want', to='categories.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategory_want', to='categories.SubCategory')),
            ],
            options={
                'verbose_name': 'Want',
                'verbose_name_plural': 'Wants',
            },
        ),
        migrations.CreateModel(
            name='WantCreateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('task', models.CharField(max_length=200, verbose_name='Task to Create')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_create_tasks', to='causeandeffects.Want')),
            ],
            options={
                'verbose_name': 'Task to Create',
                'verbose_name_plural': 'Tasks to Create',
            },
        ),
        migrations.CreateModel(
            name='WantRecommendedPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_recommended_ps_id', to='causeandeffects.Want')),
                ('practicesessions', models.ManyToManyField(related_name='want_recommended_ps', to='practice.PracticeSession')),
            ],
            options={
                'verbose_name': 'Recommended Practice Session',
                'verbose_name_plural': 'Recommended Practice Sessions',
            },
        ),
        migrations.CreateModel(
            name='WhyWant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Why Want')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_whywants', to='causeandeffects.Want')),
            ],
            options={
                'verbose_name': 'Why Want',
                'verbose_name_plural': 'Why Want',
            },
        ),
        migrations.AddField(
            model_name='selfbenefit',
            name='want',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_self_benefit', to='causeandeffects.Want'),
        ),
        migrations.AddField(
            model_name='peoplebenefit',
            name='want',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_people_benefit', to='causeandeffects.Want'),
        ),
        migrations.AddField(
            model_name='moneybenefit',
            name='want',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_money_benefit', to='causeandeffects.Want'),
        ),
    ]
