# Generated by Django 2.1 on 2019-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
