# Generated by Django 2.1 on 2019-10-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0003_powerandgrace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wantrecommendedps',
            old_name='answer',
            new_name='want',
        ),
    ]
