# Generated by Django 2.1 on 2019-10-23 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causeandeffects', '0005_userwant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('money_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_self_benefit', to='causeandeffects.MoneyBenefit')),
                ('people_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_self_benefit', to='causeandeffects.PeopleBenefit')),
                ('self_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_self_benefit', to='causeandeffects.SelfBenefit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_user_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
