# Generated by Django 2.1 on 2019-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0006_userbenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='play_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Play Video Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='ability_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Abilities Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='beliefs_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Positive Beliefs Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='ps_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Practice Sessions Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='tasks_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Tasks Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_instruction_video',
            field=models.CharField(max_length=250, null=True, verbose_name='Want Instruction Video'),
        ),
    ]
