# Generated by Django 2.1 on 2019-10-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0007_auto_20191023_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerandgrace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ability Description'),
        ),
        migrations.AlterField(
            model_name='want',
            name='ability_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Abilities Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='beliefs_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Positive Beliefs Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='play_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Play Video Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='ps_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Practice Sessions Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='tasks_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tasks Instruction Video'),
        ),
        migrations.AlterField(
            model_name='want',
            name='want_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Want Instruction Video'),
        ),
    ]
