# Generated by Django 2.1 on 2019-11-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0008_auto_20191024_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantcreatetask',
            name='pos_belief',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pos. Belief'),
        ),
        migrations.AddField(
            model_name='wantcreatetask',
            name='pos_desire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pos. Desire'),
        ),
        migrations.AddField(
            model_name='wantcreatetask',
            name='pos_expect',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pos. Expect'),
        ),
    ]
