# Generated by Django 2.1 on 2019-11-15 05:52

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0009_auto_20191115_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraceOfAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('ability', models.CharField(max_length=200, verbose_name='Ability')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ability Description')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_grace', to='causeandeffects.Want')),
            ],
            options={
                'verbose_name_plural': 'Grace of Abilities',
                'verbose_name': 'Grace of Ability',
            },
        ),
        migrations.CreateModel(
            name='PowerOfAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('ability', models.CharField(max_length=200, verbose_name='Ability')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ability Description')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_power', to='causeandeffects.Want')),
            ],
            options={
                'verbose_name_plural': 'Power of Abilities',
                'verbose_name': 'Power of Ability',
            },
        ),
        migrations.RemoveField(
            model_name='powerandgrace',
            name='want',
        ),
        migrations.DeleteModel(
            name='PowerAndGrace',
        ),
    ]
