# Generated by Django 2.1 on 2019-11-15 08:16

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
        ('practice', '0034_practicesession_purpose'),
        ('causeandeffects', '0010_auto_20191115_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalsPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fps_category_want', to='categories.Category')),
                ('practicesessions', models.ManyToManyField(related_name='fundamental_recommended_ps', to='practice.PracticeSession')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fps_subcategory_want', to='categories.SubCategory')),
            ],
            options={
                'verbose_name': 'Fundamental Practice Session',
                'verbose_name_plural': 'Fundamental Practice Sessions',
            },
        ),
    ]
