# Generated by Django 2.1 on 2019-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0011_fundamentalsps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='want',
            name='play_instruction_video',
        ),
        migrations.AddField(
            model_name='want',
            name='about_task_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='About Task Instruction Video'),
        ),
        migrations.AddField(
            model_name='want',
            name='habbit_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Habbit Instruction Video'),
        ),
    ]
