# Generated by Django 2.1 on 2019-11-15 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causeandeffects', '0012_auto_20191115_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrentHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('current_ability', models.CharField(max_length=200, verbose_name='Current Ability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_current_habit', to=settings.AUTH_USER_MODEL)),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_current_habit', to='causeandeffects.Want')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
