# Generated by Django 2.1 on 2019-11-15 12:31

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0013_usercurrenthabit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObstaclesToComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_obstacles_to_complete', to='causeandeffects.Want')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunitiesToChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_opportunities_to_change', to='causeandeffects.Want')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatIncreasesAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_what_increases_ability', to='causeandeffects.Want')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldClassAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='want_world_class_ability', to='causeandeffects.Want')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
