# Generated by Django 2.1 on 2019-11-22 05:39

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0015_auto_20191115_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('want_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Want Instruction Video')),
                ('tasks_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tasks Instruction Video')),
                ('beliefs_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Positive Beliefs Instruction Video')),
                ('ability_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Abilities Instruction Video')),
                ('ps_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Practice Sessions Instruction Video')),
                ('about_task_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='About Task Instruction Video')),
                ('habbit_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Habbit Instruction Video')),
            ],
            options={
                'verbose_name': 'Instruction Videos',
                'verbose_name_plural': 'Instruction Videos',
            },
        ),
        migrations.RemoveField(
            model_name='want',
            name='ability_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='about_task_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='beliefs_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='habbit_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='ps_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='tasks_instruction_video',
        ),
        migrations.RemoveField(
            model_name='want',
            name='want_instruction_video',
        ),
    ]
