# Generated by Django 2.1 on 2020-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0016_auto_20191122_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionvideos',
            name='about_task_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='beliefs_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='habbit_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='ps_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='tasks_instruction_video',
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='current_habits_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Habits of Ability Instruction Video'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='habitats_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Habit-ats Instruction Video'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='power_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Power & Grace Instruction Video'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='steps_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3 Steps to Turn Positive Instruction Video'),
        ),
        migrations.AlterField(
            model_name='instructionvideos',
            name='ability_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High Performance Ability Instruction Video'),
        ),
        migrations.AlterField(
            model_name='instructionvideos',
            name='want_instruction_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Want Instruction Video'),
        ),
    ]
