# Generated by Django 2.1 on 2020-02-17 04:45

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0018_auto_20200217_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='APositiveIWantInMyLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('show_more_title_1', models.CharField(max_length=70, verbose_name='Show More Title 1')),
                ('show_more_title_2', models.CharField(max_length=70, verbose_name='Show More Title 2')),
            ],
            options={
                'verbose_name': 'Positive I Want in My Life',
                'verbose_name_plural': 'Positives I Want in My Life',
            },
        ),
        migrations.AddField(
            model_name='want',
            name='positive_i_want',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want', to='causeandeffects.APositiveIWantInMyLife'),
        ),
    ]
