# Generated by Django 2.1 on 2020-02-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0019_auto_20200217_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='positive_i_want',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want', to='causeandeffects.APositiveIWantInMyLife', verbose_name='Positive I Want'),
        ),
    ]
