# Generated by Django 2.1 on 2020-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0020_auto_20200217_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='want',
            name='positive_i_want',
        ),
        migrations.AddField(
            model_name='want',
            name='positive_i_want_show_more_title_1',
            field=models.CharField(max_length=70, null=True, verbose_name='Show More Title 1'),
        ),
        migrations.AddField(
            model_name='want',
            name='positive_i_want_show_more_title_2',
            field=models.CharField(max_length=70, null=True, verbose_name='Show More Title 2'),
        ),
        migrations.DeleteModel(
            name='APositiveIWantInMyLife',
        ),
    ]
