# Generated by Django 2.1 on 2020-02-17 05:08

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0021_auto_20200217_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('first_field_title', models.CharField(max_length=70, verbose_name='1st Field Title')),
                ('first_field_content', models.CharField(max_length=300, verbose_name='1st Field Content')),
                ('second_field_title', models.CharField(max_length=70, verbose_name='2nd Field Title')),
                ('second_field_content', models.CharField(max_length=300, verbose_name='2nd Field Content')),
                ('third_field_title', models.CharField(max_length=70, verbose_name='3rd Field Title')),
                ('third_field_content', models.CharField(max_length=300, verbose_name='3rd Field Content')),
            ],
            options={
                'verbose_name_plural': 'First Level Contents',
                'verbose_name': 'First Level Content',
            },
        ),
    ]
