# Generated by Django 2.1 on 2020-02-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0022_firstlevelcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='positive_i_want_show_more_content_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want_content_1', to='causeandeffects.FirstLevelContent'),
        ),
        migrations.AddField(
            model_name='want',
            name='positive_i_want_show_more_content_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want_content_2', to='causeandeffects.FirstLevelContent'),
        ),
    ]
