# Generated by Django 2.1 on 2020-02-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0023_auto_20200217_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevelcontent',
            name='show_less_content',
            field=models.CharField(max_length=300, null=True, verbose_name='Show Content'),
        ),
        migrations.AlterField(
            model_name='want',
            name='positive_i_want_show_more_content_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want_content_1', to='causeandeffects.FirstLevelContent', verbose_name='Show More Content 1'),
        ),
        migrations.AlterField(
            model_name='want',
            name='positive_i_want_show_more_content_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_i_want_content_2', to='causeandeffects.FirstLevelContent', verbose_name='Show More Content 2'),
        ),
    ]
