# Generated by Django 2.1 on 2020-02-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0024_auto_20200217_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevelcontent',
            name='show_less_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Show Less Title'),
        ),
        migrations.AlterField(
            model_name='firstlevelcontent',
            name='show_less_content',
            field=models.CharField(max_length=300, null=True, verbose_name='Show Less Content'),
        ),
    ]
