# Generated by Django 2.1 on 2020-02-17 06:35

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0025_auto_20200217_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('positive_i_want_show_more_button_1_title', models.CharField(max_length=70, null=True, verbose_name='Show More Button 1 Title')),
                ('positive_i_want_show_more_button_2_title', models.CharField(max_length=70, null=True, verbose_name='Show More Button 2 Title')),
                ('positive_i_want_show_less_title', models.CharField(max_length=70, null=True, verbose_name='Show Less Title')),
                ('positive_i_want_first_field_title', models.CharField(max_length=70, verbose_name='1st Field Title')),
                ('positive_i_want_second_field_title', models.CharField(max_length=70, verbose_name='2nd Field Title')),
                ('positive_i_want_third_field_title', models.CharField(max_length=70, verbose_name='3rd Field Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='firstlevelcontent',
            name='first_field_title',
        ),
        migrations.RemoveField(
            model_name='firstlevelcontent',
            name='second_field_title',
        ),
        migrations.RemoveField(
            model_name='firstlevelcontent',
            name='show_less_title',
        ),
        migrations.RemoveField(
            model_name='firstlevelcontent',
            name='third_field_title',
        ),
        migrations.RemoveField(
            model_name='want',
            name='positive_i_want_show_more_title_1',
        ),
    ]
