# Generated by Django 2.1 on 2020-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0026_auto_20200217_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_first_field_title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_second_field_title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_show_less_title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_show_more_button_1_title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_show_more_button_2_title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_third_field_title',
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l1_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l1_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l1_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_section_1_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_section_1_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_section_2_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_section_2_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
    ]
