# Generated by Django 2.1 on 2020-02-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0029_auto_20200217_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s1_l1_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s1_l1_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s1_l1_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s2_l2_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s2_l2_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_s2_l2_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_section_1_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_section_1_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_section_2_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='power_and_grace_section_2_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AddField(
            model_name='want',
            name='power_and_grace_show_more_content_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_and_grace_content_1', to='causeandeffects.FirstLevelContent', verbose_name='Show More Content 1'),
        ),
        migrations.AddField(
            model_name='want',
            name='power_and_grace_show_more_content_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_and_grace_content_2', to='causeandeffects.FirstLevelContent', verbose_name='Show More Content 2'),
        ),
    ]
