# Generated by Django 2.1 on 2020-02-17 10:45

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0033_auto_20200217_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondLevelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('first_f1_show_more_text', models.CharField(max_length=300, verbose_name='1st Field Text')),
                ('second_f1_show_more_text', models.CharField(max_length=300, verbose_name='2nd Field  Text')),
                ('third_f1_show_more_text', models.CharField(max_length=300, verbose_name='3rd Field Text')),
                ('first_f2_show_more_text', models.CharField(max_length=300, verbose_name='1st Field Text')),
                ('second_f2_show_more_text', models.CharField(max_length=300, verbose_name='2nd Field  Text')),
                ('third_f2_show_more_text', models.CharField(max_length=300, verbose_name='3rd Field Text')),
                ('first_f3_show_more_text', models.CharField(max_length=300, verbose_name='1st Field Text')),
                ('second_f3_show_more_text', models.CharField(max_length=300, verbose_name='2nd Field  Text')),
                ('third_f3_show_more_text', models.CharField(max_length=300, verbose_name='3rd Field Text')),
                ('first_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_and_second_level_fk', to='causeandeffects.FirstLevelContent', verbose_name='First Level')),
            ],
            options={
                'verbose_name': 'Second Level Content',
                'verbose_name_plural': 'Second Level Contents',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l2_1f_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 1st Field: Header Title'),
        ),
    ]
