# Generated by Django 2.1 on 2020-02-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0034_auto_20200217_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondlevelcontent',
            name='first_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_and_second_level_fk', to='causeandeffects.FirstLevelContent', verbose_name='First Level'),
        ),
    ]
