# Generated by Django 2.1 on 2020-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0036_auto_20200217_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondlevelcontent',
            name='first_2l_field_content',
        ),
        migrations.RemoveField(
            model_name='secondlevelcontent',
            name='second_2l_field_content',
        ),
        migrations.RemoveField(
            model_name='secondlevelcontent',
            name='third_2l_field_content',
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='first_f1_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='first_f2_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='first_f3_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='second_f1_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='second_f2_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='second_f3_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='third_f1_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='third_f2_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='secondlevelcontent',
            name='third_f3_show_more_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
    ]
