# Generated by Django 2.1 on 2020-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0037_auto_20200217_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s1_l2_1f_header_title',
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l2_f1_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 1st Field: Header Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l2_f2_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 2nd Field: Header Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s1_l2_f3_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 3rd Field: Header Title'),
        ),
    ]
