# Generated by Django 2.1 on 2020-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0038_auto_20200217_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_habits_of_ability_section_1_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_habits_of_ability_section_1_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='habitats_outside_of_me_section_1_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='habitats_outside_of_me_section_1_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='high_performance_ability_s1_l1_first_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='high_performance_ability_s1_l1_second_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='high_performance_ability_s1_l1_third_field_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='high_performance_ability_section_1_button_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='high_performance_ability_section_1_show_less_text',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
    ]
