# Generated by Django 2.1 on 2020-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0039_auto_20200217_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_f1_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 1st Field: Header Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_f2_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 2nd Field: Header Title'),
        ),
        migrations.AddField(
            model_name='settings',
            name='positive_i_want_s2_l2_f3_header_title',
            field=models.CharField(max_length=70, null=True, verbose_name='Section 1: 2nd Level: 3rd Field: Header Title'),
        ),
    ]
