# Generated by Django 2.1 on 2020-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0040_auto_20200217_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='current_habits_of_ability_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='habitats_outside_of_me_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='high_performance_ability_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l2_f1_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 1st Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l2_f2_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 2nd Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s1_l2_f3_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 3rd Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_f1_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 1st Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_f2_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 2nd Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_f3_header_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 2nd Level: 3rd Field: Header Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='positive_i_want_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_and_grace_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s1_l1_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s1_l1_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s1_l1_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s2_l2_first_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 1st Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s2_l2_second_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 2nd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_s2_l2_third_field_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: 1st Level: 3rd Field Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_section_1_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_section_1_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 1: Show Less Title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_section_2_button_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Button Text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steps_to_turn_positive_section_2_show_less_text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Section 2: Show Less Title'),
        ),
    ]
