# Generated by Django 2.1 on 2020-02-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0042_thirdlevelcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdlevelcontent',
            name='second_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_and_third_level_fk', to='causeandeffects.SecondLevelContent', verbose_name='Second Level'),
        ),
    ]
