# Generated by Django 2.1 on 2020-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0044_auto_20200217_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='first_f1_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='first_f2_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='first_f3_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='second_f1_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='second_f2_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='second_f3_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='third_f1_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='third_f2_show_more_text',
        ),
        migrations.RemoveField(
            model_name='thirdlevelcontent',
            name='third_f3_show_more_text',
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_1st_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_1st_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_1st_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_2nd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_2nd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_2nd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_3rd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_3rd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f1_3rd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_1st_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_1st_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_1st_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_2nd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_2nd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_2nd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_3rd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_3rd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f2_3rd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_1st_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_1st_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_1st_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_2nd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_2nd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_2nd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_3rd_f1_text',
            field=models.CharField(max_length=300, null=True, verbose_name='1st Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_3rd_f2_text',
            field=models.CharField(max_length=300, null=True, verbose_name='2nd Field Text'),
        ),
        migrations.AddField(
            model_name='thirdlevelcontent',
            name='f3_3rd_f3_text',
            field=models.CharField(max_length=300, null=True, verbose_name='3rd Field Text'),
        ),
    ]
