# Generated by Django 2.1 on 2020-04-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0051_auto_20200220_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forthlevelcontent',
            name='third_level',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s1_l3_button1_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s1_l3_button2_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s1_l3_button3_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s2_l3_button1_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s2_l3_button2_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='positive_i_want_s2_l3_button3_text',
        ),
        migrations.DeleteModel(
            name='ForthLevelContent',
        ),
    ]
