# Generated by Django 2.1 on 2020-06-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbers', '0006_auto_20200630_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
    ]
