# Generated by Django 2.1 on 2020-06-15 13:01

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('low_low', models.CharField(max_length=200, verbose_name='low first')),
                ('low_high', models.CharField(max_length=200, verbose_name='low second')),
                ('low_medium', models.CharField(max_length=200, verbose_name='low third')),
                ('high_low', models.CharField(max_length=200, verbose_name='high first')),
                ('high_high', models.CharField(max_length=200, verbose_name='high second')),
                ('high_medium', models.CharField(max_length=200, verbose_name='high third')),
                ('medium_low', models.CharField(max_length=200, verbose_name='medium first')),
                ('medium_high', models.CharField(max_length=200, verbose_name='medium second')),
                ('medium_medium', models.CharField(max_length=200, verbose_name='medium third')),
                ('polarity_self_talk', models.CharField(max_length=200, null=True, verbose_name='polarity')),
                ('function_self_talk', models.CharField(max_length=200, null=True, verbose_name='function')),
                ('emotion_self_talk', models.CharField(max_length=200, null=True, verbose_name='emotion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_st', to='categories.Category', verbose_name='Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_st', to='categories.SubCategory', verbose_name='SubCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('userId', models.IntegerField(default=0, verbose_name='User Id')),
                ('before', models.CharField(max_length=50, null=True, verbose_name='Before')),
                ('during', models.CharField(max_length=50, null=True, verbose_name='During')),
                ('after', models.CharField(max_length=50, null=True, verbose_name='After')),
                ('who_am_i_talking_to', models.CharField(max_length=50, null=True, verbose_name='Who am i talking to')),
                ('is_now_a_good_time_to_talk', models.CharField(max_length=50, null=True, verbose_name='Is now a good time to talk to this person in my head')),
                ('times_a_day', models.CharField(max_length=50, null=True, verbose_name='Times a day')),
                ('times_it_last', models.CharField(max_length=50, null=True, verbose_name='Times it Last')),
                ('how_intense', models.CharField(max_length=50, null=True, verbose_name='How intense')),
                ('polarity', models.CharField(max_length=50, null=True, verbose_name='Polarity')),
                ('function', models.CharField(max_length=50, null=True, verbose_name='Function')),
                ('emotion', models.CharField(max_length=50, null=True, verbose_name='Emotion')),
                ('selftalk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selftalk_fk', to='selftalk.SelfTalk', verbose_name='Selftalk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
