# Generated by Django 2.1 on 2019-08-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('awareness', '0002_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_awareness', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_awareness', to='categories.SubCategory'),
        ),
    ]
