# Generated by Django 2.1 on 2019-08-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0003_auto_20190830_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
