# Generated by Django 2.1 on 2019-09-02 11:11

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0022_auto_20190830_1646'),
        ('awareness', '0004_remove_answer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('affirmations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='awareness_answers', to='practice.Affirmation')),
            ],
            options={
                'verbose_name_plural': '2. Add Affirmations',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='videoLink',
            field=models.CharField(default='', max_length=500, verbose_name='Video Link'),
        ),
        migrations.AddField(
            model_name='affirmations',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_contents', to='awareness.Answer'),
        ),
    ]
