# Generated by Django 2.1 on 2019-09-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0005_auto_20190902_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name_plural': 'Text'},
        ),
    ]
