# Generated by Django 2.1 on 2019-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0006_auto_20190903_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='OTCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
    ]
