# Generated by Django 2.1 on 2019-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0007_answer_otctext'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='OTCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='OTCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='answer',
            name='OTCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
    ]
