# Generated by Django 2.1 on 2019-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0008_auto_20190903_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ITCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ITCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ITCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ITCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
    ]
