# Generated by Django 2.1 on 2019-09-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0009_auto_20190903_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='NTCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='NTCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='NTCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='answer',
            name='NTCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
    ]
