# Generated by Django 2.1 on 2019-09-04 10:52

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0023_auto_20190903_1030'),
        ('awareness', '0010_auto_20190903_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_contents', to='awareness.Answer')),
                ('practicesessions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='awareness_practicesessions', to='practice.PracticeSession')),
            ],
            options={
                'verbose_name': 'Recommended Practice Session',
                'verbose_name_plural': 'Recommended Practice Sessions',
            },
        ),
        migrations.RemoveField(
            model_name='affirmations',
            name='affirmations',
        ),
        migrations.RemoveField(
            model_name='affirmations',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Affirmations',
        ),
    ]
