# Generated by Django 2.1 on 2019-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0023_auto_20190903_1030'),
        ('awareness', '0011_auto_20190904_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesessions',
            name='practicesessions',
        ),
        migrations.AddField(
            model_name='practicesessions',
            name='practicesessions',
            field=models.ManyToManyField(related_name='awareness_practicesessions', to='practice.PracticeSession'),
        ),
    ]
