# Generated by Django 2.1 on 2019-09-08 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0023_auto_20190903_1030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awareness', '0013_auto_20190906_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_contents', to='awareness.Answer')),
                ('practicesessions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='awareness_practicesessions', to='practice.PracticeSession')),
            ],
            options={
                'verbose_name_plural': 'Recommended Practice Sessions',
                'verbose_name': 'Recommended Practice Session',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ManyToManyField(related_name='user_answers', to='awareness.Answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='awareness.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Answers',
                'verbose_name': 'User Answer',
            },
        ),
        migrations.RemoveField(
            model_name='recommendedps',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recommendedps',
            name='practicesessions',
        ),
        migrations.DeleteModel(
            name='RecommendedPS',
        ),
    ]
