# Generated by Django 2.1 on 2019-09-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0015_auto_20190911_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedps',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recommendedps',
            name='practicesessions',
        ),
        migrations.DeleteModel(
            name='RecommendedPS',
        ),
    ]
