# Generated by Django 2.1 on 2019-09-14 06:18

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0018_auto_20190914_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.TextField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_questions', to='awareness.Space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
