# Generated by Django 2.1 on 2019-09-14 07:26

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0019_spacequestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.CharField(default='', max_length=500, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Space Answer',
                'verbose_name_plural': 'Space Answers',
            },
        ),
        migrations.AlterModelOptions(
            name='spacequestions',
            options={'verbose_name': 'Space Question', 'verbose_name_plural': 'Space Questions'},
        ),
        migrations.AlterField(
            model_name='spacequestions',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_question_answers', to='awareness.SpaceQuestions'),
        ),
    ]
