# Generated by Django 2.1 on 2019-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0020_auto_20190914_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaceanswers',
            options={'verbose_name': 'Space: Answer', 'verbose_name_plural': 'Space: Answers'},
        ),
        migrations.AlterModelOptions(
            name='spacequestions',
            options={'verbose_name': 'Space: Question', 'verbose_name_plural': 'Space: Questions'},
        ),
        migrations.RemoveField(
            model_name='spacequestions',
            name='text',
        ),
        migrations.AddField(
            model_name='spacequestions',
            name='question',
            field=models.CharField(default='', max_length=500, verbose_name='Question'),
        ),
    ]
