# Generated by Django 2.1 on 2019-09-16 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awareness', '0021_auto_20190914_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceQuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ManyToManyField(related_name='space_user_answers', to='awareness.SpaceAnswers')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_question_id', to='awareness.SpaceQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Space: User Answer',
                'verbose_name_plural': 'Space: User Answers',
            },
        ),
    ]
