# Generated by Django 2.1 on 2019-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0022_spacequestionanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceanswers',
            name='ITCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='ITCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='ITCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='ITCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='NTCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='NTCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='NTCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='NTCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='OTCIntensity',
            field=models.CharField(default='', max_length=25, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='OTCText',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='OTCThinkEachTime',
            field=models.IntegerField(default=0, verbose_name='How long think it each time'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='OTCThinkPerDay',
            field=models.IntegerField(default=0, verbose_name='How often think it/day'),
        ),
        migrations.AddField(
            model_name='spaceanswers',
            name='videoLink',
            field=models.CharField(default='', max_length=500, verbose_name='Video Link'),
        ),
    ]
