# Generated by Django 2.1 on 2019-09-19 05:50

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0026_auto_20190917_1348'),
        ('awareness', '0023_auto_20190918_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceRecommendedPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_answer_contents', to='awareness.SpaceAnswers')),
                ('practicesessions', models.ManyToManyField(related_name='space_awareness_ps_recommended', to='practice.PracticeSession')),
            ],
            options={
                'verbose_name': 'Recommended Practice Session',
                'verbose_name_plural': 'Recommended Practice Sessions',
            },
        ),
    ]
