# Generated by Django 2.1 on 2019-09-19 13:06

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0024_spacerecommendedps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceTextBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='space_text_boxes', to='awareness.Space')),
            ],
            options={
                'verbose_name_plural': 'Spaces',
                'verbose_name': 'Space',
            },
        ),
    ]
