# Generated by Django 2.1 on 2019-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0025_spacetextboxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacetextboxes',
            old_name='name',
            new_name='text',
        ),
    ]
