# Generated by Django 2.1 on 2019-09-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0026_auto_20190919_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacetextboxes',
            options={'verbose_name': 'Text Box', 'verbose_name_plural': 'Text Boxes'},
        ),
    ]
