# Generated by Django 2.1 on 2019-09-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0027_auto_20190919_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
