# Generated by Django 2.1 on 2019-09-19 14:26

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0028_auto_20190919_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessTextBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Awareness Text Box',
                'verbose_name_plural': 'Awareness Text Boxes',
            },
        ),
    ]
