# Generated by Django 2.1 on 2019-09-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0029_awarenesstextboxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awarenesstextboxes',
            options={'verbose_name': '3. Awareness Text Box', 'verbose_name_plural': '3. Awareness Text Boxes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': "1. 3 A's of Life: Question", 'verbose_name_plural': "1. 3 A's of Life: Questions"},
        ),
    ]
