# Generated by Django 2.1 on 2019-09-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0030_auto_20190926_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': "1. 3 A's of Life: Answer", 'verbose_name_plural': "1. 3 A's of Life: Answers"},
        ),
        migrations.AlterModelOptions(
            name='spaceanswers',
            options={'verbose_name': '5. Space: Answer', 'verbose_name_plural': '5. Space: Answers'},
        ),
        migrations.AlterModelOptions(
            name='spacequestions',
            options={'verbose_name': '4. Space: Question', 'verbose_name_plural': '4. Space: Questions'},
        ),
    ]
