# Generated by Django 2.1 on 2019-09-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0031_auto_20190926_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': '3. Space', 'verbose_name_plural': '3. Spaces'},
        ),
    ]
