# Generated by Django 2.1 on 2019-09-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0032_auto_20190926_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '1. 3 As of Life: Answer', 'verbose_name_plural': '1. 3 As of Life: Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '1. 3 As of Life: Question', 'verbose_name_plural': '1. 3 As of Life: Questions'},
        ),
    ]
