# Generated by Django 2.1 on 2019-09-27 07:24

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0033_auto_20190926_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('fundamentalKnowledge', models.TextField(verbose_name='Fundamental Knowledge')),
                ('detailedKnowledge', models.TextField(verbose_name='Detailed Knowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
