# Generated by Django 2.1 on 2019-09-27 08:14

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190830_1646'),
        ('awareness', '0034_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('fundamentalKnowledge', models.TextField(verbose_name='Fundamental Knowledge')),
                ('knowledgePage', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundamental_knowledge', to='knowledge.Knowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='fundamentalKnowledge',
        ),
    ]
