# Generated by Django 2.1 on 2019-09-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0035_auto_20190927_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='fundamentalKnowledge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_knowledge_fk', to='awareness.FundamentalKnowledge'),
        ),
    ]
