# Generated by Django 2.1 on 2019-09-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0036_timeline_fundamentalknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='fundamentalKnowledge',
        ),
    ]
