# Generated by Django 2.1 on 2019-09-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0037_remove_timeline_fundamentalknowledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundamentalknowledge',
            old_name='fundamentalKnowledge',
            new_name='text',
        ),
        migrations.AddField(
            model_name='timeline',
            name='fundamentalKnowledge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_knowledge_oto', to='awareness.FundamentalKnowledge'),
        ),
    ]
