# Generated by Django 2.1 on 2019-09-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0038_auto_20190927_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='fundamentalKnowledge',
        ),
        migrations.AddField(
            model_name='fundamentalknowledge',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_timeline_fk', to='awareness.Timeline'),
        ),
    ]
