# Generated by Django 2.1 on 2019-09-27 09:31

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190830_1646'),
        ('awareness', '0039_auto_20190927_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.TextField(verbose_name='Detailed Knowledge')),
                ('knowledgePage', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailed_knowledge', to='knowledge.Knowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='detailedKnowledge',
        ),
        migrations.AddField(
            model_name='detailedknowledge',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dk_timeline_fk', to='awareness.Timeline'),
        ),
    ]
