# Generated by Django 2.1 on 2019-09-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0040_auto_20190927_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': '6. Timeline', 'verbose_name_plural': '6. Timelines'},
        ),
    ]
