# Generated by Django 2.1 on 2019-09-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0041_auto_20190927_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '2. 3 As of Life: Answer', 'verbose_name_plural': '2. 3 As of Life: Answers'},
        ),
    ]
