# Generated by Django 2.1 on 2019-09-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190830_1646'),
        ('awareness', '0042_auto_20190927_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedknowledge',
            name='knowledgePage',
        ),
        migrations.RemoveField(
            model_name='detailedknowledge',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='fundamentalknowledge',
            name='knowledgePage',
        ),
        migrations.RemoveField(
            model_name='fundamentalknowledge',
            name='timeline',
        ),
        migrations.AddField(
            model_name='timeline',
            name='detailedKnowledge',
            field=models.TextField(default='', verbose_name='Detailed Knowledge'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='detailedKnowledgePage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailed_knowledge', to='knowledge.Knowledge', verbose_name='Detailed Knowledge Page'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='fundamentalKnowledge',
            field=models.TextField(default='', verbose_name='Fundamental Knowledge'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='fundamentalKnowledgePage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundamental_knowledge', to='knowledge.Knowledge', verbose_name='Fundamental Knowledge Page'),
        ),
        migrations.DeleteModel(
            name='DetailedKnowledge',
        ),
        migrations.DeleteModel(
            name='FundamentalKnowledge',
        ),
    ]
