# Generated by Django 2.1 on 2019-09-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awareness', '0043_auto_20190927_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('starttime', models.TimeField(verbose_name='Start Time')),
                ('endtime', models.TimeField(verbose_name='End Time')),
                ('timeline', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_timeline_fk', to='awareness.Timeline', verbose_name='Timeline Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_user_id', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Timelines',
                'verbose_name': 'User Timeline',
            },
        ),
        migrations.AlterField(
            model_name='spacequestionanswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='space_question_id', to='awareness.SpaceQuestions'),
        ),
        migrations.AlterField(
            model_name='spacequestionanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='space_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
