# Generated by Django 2.1 on 2019-09-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0044_auto_20190930_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='detailedKnowledgePage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailed_knowledge', to='knowledge.Knowledge', verbose_name='Detailed Knowledge Page'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='fundamentalKnowledgePage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundamental_knowledge', to='knowledge.Knowledge', verbose_name='Fundamental Knowledge Page'),
        ),
    ]
