# Generated by Django 2.1 on 2019-09-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0045_auto_20190930_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_timeline_fk', to='awareness.Timeline', verbose_name='Timeline Name'),
        ),
    ]
