# Generated by Django 2.1 on 2019-10-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
        ('awareness', '0046_auto_20190930_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_timeline_category_fk', to='categories.Category', verbose_name='Category Name'),
        ),
    ]
