# Generated by Django 2.1 on 2018-08-06 06:43

import django.db.models.deletion
from django.db import migrations, models

import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffirmationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('order', models.IntegerField(default=1)),
                ('text', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='affirmation',
            name='text',
        ),
        migrations.AddField(
            model_name='affirmation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_bundles', to='practice.Category'),
        ),
        migrations.AddField(
            model_name='affirmation',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.AddField(
            model_name='affirmationtext',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmation_texts', to='practice.Affirmation'),
        ),
    ]
