# Generated by Django 2.1 on 2018-08-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20180806_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_affirmations', to='practice.SubCategory'),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_affirmations', to='practice.Category'),
        ),
    ]
