# Generated by Django 2.1 on 2018-08-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import iow.apps.core.models
import iow.apps.practice.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0003_auto_20180806_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='order',
            field=models.IntegerField(default=iow.apps.practice.models.order_next_number_affirmation),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='affirmations_in_practice_sessions', to='practice.Affirmation'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
