# Generated by Django 2.1 on 2018-08-08 21:40

from django.db import migrations, models

import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20180808_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('related_tags', models.CharField(help_text='comma separated words e.g. happy, money', max_length=200)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('practice_session', models.ManyToManyField(related_name='practice_session_images', to='practice.PracticeSession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
