# Generated by Django 2.1 on 2018-08-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='music_file',
            field=models.FileField(default='', upload_to='mp3s/%Y/%m/%d'),
        ),
    ]
