# Generated by Django 2.1 on 2018-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_practicesession_music_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affirmation',
            options={'verbose_name_plural': '3. Affirmations'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': '5. Images for Practice Sessions'},
        ),
        migrations.AlterModelOptions(
            name='practicesession',
            options={'verbose_name_plural': '4. Practice Sessions'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '2. Sub Category'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
