# Generated by Django 2.1 on 2018-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_auto_20180815_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='music_file',
            field=models.FileField(blank=True, default='', upload_to='mp3s/%Y/%m/%d'),
        ),
    ]
