# Generated by Django 2.1 on 2018-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_auto_20180815_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='duration_in_secs',
            field=models.IntegerField(default=3),
        ),
    ]
