# Generated by Django 2.1 on 2018-08-19 10:07

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_auto_20180818_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': '6. User Packs'},
        ),
        migrations.RemoveField(
            model_name='pack',
            name='practice_session',
        ),
        migrations.AddField(
            model_name='packsession',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sessions', to='practice.Pack'),
        ),
        migrations.AddField(
            model_name='packsession',
            name='practice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_packs', to='practice.PracticeSession'),
        ),
    ]
