# Generated by Django 2.1 on 2018-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_auto_20180819_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
