# Generated by Django 2.1 on 2018-08-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_auto_20180819_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
