# Generated by Django 2.1 on 2018-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_image_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='packsession',
            name='fulfilment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packsession',
            name='last_time_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packsession',
            name='repeated',
            field=models.IntegerField(default=0),
        ),
    ]
