# Generated by Django 2.1 on 2018-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_auto_20180824_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='packsession',
            name='spent_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
