# Generated by Django 2.1 on 2018-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0015_packsession_spent_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicesession',
            options={'ordering': ['order'], 'verbose_name_plural': '4. Practice Sessions'},
        ),
        migrations.AddField(
            model_name='practicesession',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
