# Generated by Django 2.1 on 2018-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0016_auto_20180827_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
