# Generated by Django 2.1 on 2018-09-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0017_auto_20180827_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packsession',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='packsession',
            name='practice_session',
        ),
        migrations.AddField(
            model_name='pack',
            name='practice_sessions',
            field=models.ManyToManyField(related_name='ps_in_packs', to='practice.PracticeSession'),
        ),
        migrations.DeleteModel(
            name='PackSession',
        ),
    ]
