# Generated by Django 2.1 on 2019-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_auto_20180907_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='duration_in_secs',
            field=models.IntegerField(default=24),
        ),
    ]
