# Generated by Django 2.1 on 2019-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0019_auto_20190821_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='font_size',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='duration_in_secs',
            field=models.IntegerField(default=3),
        ),
    ]
