# Generated by Django 2.1 on 2019-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0020_auto_20190821_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='brightness',
            field=models.IntegerField(default=100),
        ),
    ]
