# Generated by Django 2.1 on 2019-09-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0022_auto_20190830_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affirmation',
            options={'verbose_name_plural': 'Affirmations'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Images for Practice Sessions'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': 'User Packs'},
        ),
        migrations.AlterModelOptions(
            name='practicesession',
            options={'ordering': ['order'], 'verbose_name_plural': 'Practice Sessions'},
        ),
    ]
