# Generated by Django 2.1 on 2019-09-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0024_auto_20190917_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affirmations_in_practice_sessions', to='practice.Affirmation'),
        ),
    ]
