# Generated by Django 2.1 on 2019-09-17 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0025_auto_20190917_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='affirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmations_in_practice_sessions', to='practice.Affirmation'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
