# Generated by Django 2.1 on 2019-09-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0027_affirmationtext_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmationtext',
            name='cells',
            field=models.IntegerField(default=0, verbose_name='Cells'),
        ),
        migrations.AddField(
            model_name='affirmationtext',
            name='repetition',
            field=models.IntegerField(default=0, verbose_name='Repetitions'),
        ),
    ]
