# Generated by Django 2.1 on 2019-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0028_auto_20190925_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmationtext',
            name='cells',
            field=models.IntegerField(default=1, verbose_name='Cells'),
        ),
    ]
