# Generated by Django 2.1 on 2019-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0029_auto_20190925_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmationtext',
            name='repetition',
            field=models.IntegerField(default=1, verbose_name='Repetitions'),
        ),
    ]
