# Generated by Django 2.1 on 2019-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0030_auto_20190925_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmationtext',
            name='mantra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
