# Generated by Django 2.1 on 2019-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0031_affirmationtext_mantra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmationtext',
            name='mantra',
            field=models.TextField(default=''),
        ),
    ]
