# Generated by Django 2.1 on 2019-10-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0032_auto_20191004_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='duration_in_secs',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='font_size',
        ),
    ]
