# Generated by Django 2.1 on 2019-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0033_auto_20191008_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
