# Generated by Django 2.1 on 2018-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverpage',
            name='title',
            field=models.TextField(default='Discover Your Horizons'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='headline',
            field=models.TextField(default='Ability & Habit Improving Technology 4 Me'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='text',
            field=models.TextField(default='Technology to Improve Your Habits of Abilities to Improve Your life. Use Your Thoughts to Create the Habits You Need to Enjoy the Life You Desire'),
        ),
    ]
