# Generated by Django 2.1 on 2019-12-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20181014_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscoverPage',
        ),
    ]
