# Generated by Django 2.1 on 2018-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
