# Generated by Django 2.1 on 2018-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_payment_subscription_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
