# Generated by Django 2.1 on 2018-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180904_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='the_subscription_id',
            field=models.IntegerField(null=True),
        ),
    ]
