# Generated by Django 2.1 on 2018-09-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_the_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='the_subscription_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
