# Generated by Django 2.1 on 2019-10-01 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180907_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timeline_endtime',
            field=models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Timeline End Time'),
        ),
        migrations.AddField(
            model_name='profile',
            name='timeline_starttime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Timeline Start Time'),
        ),
    ]
