# Generated by Django 2.1 on 2019-10-08 05:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_auto_20191001_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('timeline_starttime', models.TimeField(default=datetime.time(0, 0), verbose_name='Timeline Start Time')),
                ('timeline_endtime', models.TimeField(default=datetime.time(23, 59, 59), verbose_name='Timeline End Time')),
                ('duration_in_secs', models.IntegerField(default=3)),
                ('font_size', models.IntegerField(default=24)),
                ('brightness', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timeline_endtime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timeline_starttime',
        ),
    ]
