# Generated by Django 2.1 on 2019-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191008_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ps_cycles',
            field=models.IntegerField(default=1),
        ),
    ]
