# Generated by Django 2.1 on 2019-10-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_usersettings_ps_cycles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
    ]
