# Generated by Django 2.1 on 2019-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20191127_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
