# Generated by Django 2.1 on 2020-04-16 07:51

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('stripe_subscription_id', models.CharField(max_length=60)),
                ('stripe_subscription_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
