# Generated by Django 2.1 on 2020-04-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscription',
            old_name='stripe_subscription_date',
            new_name='ustripe_subscription_date',
        ),
        migrations.RenameField(
            model_name='user_subscription',
            old_name='stripe_subscription_id',
            new_name='ustripe_subscription_id',
        ),
    ]
