# Generated by Django 2.1 on 2019-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='coverText',
            field=models.TextField(default='', null=True),
        ),
    ]
