# Generated by Django 2.1 on 2019-09-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory_covertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='coverText',
        ),
    ]
