# Generated by Django 2.1 on 2019-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_subcategory_covertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='ImageText',
            field=models.TextField(default='', verbose_name='Image Text'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='Cover Image'),
        ),
    ]
