# Generated by Django 2.1 on 2019-09-19 13:53

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190916_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatTextBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Text Boxes',
                'verbose_name': 'Text Box',
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='ImageText',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='subcattextboxes',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_cat_text_boxes', to='categories.SubCategory'),
        ),
    ]
