# Generated by Django 2.1 on 2019-10-29 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0005_auto_20190919_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Behavior')),
            ],
            options={
                'verbose_name_plural': 'Behaviors',
                'verbose_name': 'Behavior',
            },
        ),
        migrations.CreateModel(
            name='Believe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Believe Name')),
            ],
            options={
                'verbose_name_plural': 'Current Reality Believes',
                'verbose_name': 'Current Reality Believe',
            },
        ),
        migrations.CreateModel(
            name='ContentOfSelfTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Content of Self Talk')),
            ],
            options={
                'verbose_name_plural': 'Contents of Self Talk',
                'verbose_name': 'Content of Self Talk',
            },
        ),
        migrations.CreateModel(
            name='IdentifyCurrentReality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Reality')),
                ('order', models.IntegerField(default=0)),
                ('want_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Current Reality Instruction Video Link')),
                ('isth_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Self-talk Instruction Video Link')),
                ('ibh_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Behavior Instruction Video Link')),
                ('ihyli_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Habitats Instruction Video Link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_current_reality', to='categories.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategory_current_reality', to='categories.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Identify Current Realities',
                'verbose_name': 'Identify Current Reality',
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Thought')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thought_current_reality', to='causalforces.IdentifyCurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Thoughts',
                'verbose_name': 'Thought',
            },
        ),
        migrations.CreateModel(
            name='UserBelieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('believe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='believe_user_believes', to='causalforces.Believe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_user_believes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIdentifyBehaviorHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('aware_before', models.CharField(max_length=25, verbose_name='Aware Before')),
                ('aware_during', models.CharField(max_length=25, verbose_name='Aware During')),
                ('aware_after', models.CharField(max_length=25, verbose_name='Aware After')),
                ('intent_of_self_talk', models.TextField(verbose_name='Intent of Self Talk')),
                ('polarity', models.CharField(max_length=25, verbose_name='Polarity')),
                ('function', models.CharField(max_length=25, verbose_name='Function')),
                ('emotion', models.CharField(max_length=25, verbose_name='Emotion')),
                ('intensity', models.CharField(max_length=25, verbose_name='Intensity')),
                ('effect', models.CharField(max_length=25, verbose_name='Effect')),
                ('how_long', models.CharField(max_length=25, verbose_name='How Long Each Time')),
                ('often_think_day', models.CharField(max_length=25, verbose_name='Often Think Day')),
                ('often_think_wk', models.CharField(max_length=25, verbose_name='Often Think Week')),
                ('who_talking_to', models.CharField(max_length=100, verbose_name='Who Talking to')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ibh_behavior', to='causalforces.Behavior')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_identify_behavior_habits_cr', to='causalforces.IdentifyCurrentReality')),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ibh_thought', to='causalforces.Thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ibh_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIdentifyHabitatsYouLiveIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('pct_mindful_positive', models.IntegerField(verbose_name='% mindful positive clear')),
                ('pct_mindful_neutral', models.IntegerField(verbose_name='% mindful Neutral clear')),
                ('pct_mindful_negative', models.IntegerField(verbose_name='% mindful Negative clear')),
                ('dmp_identify_habitats', models.CharField(max_length=50, verbose_name='Daily Minutes Practicing')),
                ('pct_flow_positive', models.IntegerField(verbose_name='% Positive Flow to Want to Act')),
                ('pct_flow_neutral', models.IntegerField(verbose_name='% Neutral Flow to Be OK')),
                ('pct_flow_negative', models.IntegerField(verbose_name='% Negative Flow to Sit & Stress')),
                ('dmp_flow_habitats', models.CharField(max_length=50, verbose_name='Daily Minutes Practicing')),
                ('identity_habitat', models.CharField(max_length=200, verbose_name='Identify Habitat')),
                ('is_place_card_for', models.CharField(max_length=200, verbose_name='Is Place Cared for')),
                ('am_i_appreciating', models.CharField(max_length=50, verbose_name='Am I Appreciating')),
                ('future_project', models.CharField(max_length=50, verbose_name='Would I like to select as future project')),
                ('daily_minutes_for_caring', models.CharField(max_length=50, verbose_name='Daily Minutes caring for')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ihyli_cr', to='causalforces.IdentifyCurrentReality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ihyli_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIdentifySelfTalkHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('aware_before', models.CharField(max_length=25, verbose_name='Aware Before')),
                ('aware_during', models.CharField(max_length=25, verbose_name='Aware During')),
                ('aware_after', models.CharField(max_length=25, verbose_name='Aware After')),
                ('intent_of_self_talk', models.TextField(verbose_name='Intent of Self Talk')),
                ('polarity', models.CharField(max_length=25, verbose_name='Polarity')),
                ('function', models.CharField(max_length=25, verbose_name='Function')),
                ('emotion', models.CharField(max_length=25, verbose_name='Emotion')),
                ('intensity', models.CharField(max_length=25, verbose_name='Intensity')),
                ('effect', models.CharField(max_length=25, verbose_name='Effect')),
                ('how_long', models.CharField(max_length=25, verbose_name='How Long Each Time')),
                ('often_think_day', models.CharField(max_length=25, verbose_name='Often Think Day')),
                ('often_think_wk', models.CharField(max_length=25, verbose_name='Often Think Week')),
                ('who_talking_to', models.CharField(max_length=100, verbose_name='Who Talking to')),
                ('content_of_self_talk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_identify_self_talk_habits_cst', to='causalforces.ContentOfSelfTalk')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_identify_self_talk_habits_cr', to='causalforces.IdentifyCurrentReality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_identify_self_talk_habits_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentofselftalk',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_reality_content_of_self_talk', to='causalforces.IdentifyCurrentReality'),
        ),
        migrations.AddField(
            model_name='believe',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_reality_believe', to='causalforces.IdentifyCurrentReality'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='behavior_current_reality', to='causalforces.IdentifyCurrentReality'),
        ),
    ]
