# Generated by Django 2.1 on 2019-10-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifycurrentreality',
            options={'verbose_name': 'Current Reality', 'verbose_name_plural': 'Current Realities'},
        ),
    ]
