# Generated by Django 2.1 on 2019-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
        ('causalforces', '0002_auto_20191029_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentifyCurrentReality',
            new_name='CurrentReality',
        ),
    ]
