# Generated by Django 2.1 on 2019-10-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0003_auto_20191030_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentreality',
            old_name='want_instruction_video',
            new_name='cr_instruction_video',
        ),
    ]
