# Generated by Django 2.1 on 2019-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0005_auto_20191030_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_flow_negative',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% Negative Flow to Sit & Stress'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_flow_neutral',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% Neutral Flow to Be OK'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_flow_positive',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% Positive Flow to Want to Act'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_mindful_negative',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% mindful Negative clear'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_mindful_neutral',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% mindful Neutral clear'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='pct_mindful_positive',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='% mindful positive clear'),
        ),
    ]
