# Generated by Django 2.1 on 2019-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0006_auto_20191031_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='aware_after',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware After'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='aware_before',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware Before'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='aware_during',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware During'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='effect',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='emotion',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='function',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='how_long',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='How Long Each Time'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='intensity',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Intensity'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='intent_of_self_talk',
            field=models.TextField(blank=True, null=True, verbose_name='Intent of Self Talk'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='often_think_day',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Often Think Day'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='often_think_wk',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Often Think Week'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='polarity',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='who_talking_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Who Talking to'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='aware_after',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware After'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='aware_before',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware Before'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='aware_during',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Aware During'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='effect',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='emotion',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='function',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='how_long',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='How Long Each Time'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='intensity',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Intensity'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='intent_of_self_talk',
            field=models.TextField(blank=True, null=True, verbose_name='Intent of Self Talk'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='often_think_day',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Often Think Day'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='often_think_wk',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Often Think Week'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='polarity',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='who_talking_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Who Talking to'),
        ),
    ]
