# Generated by Django 2.1 on 2019-10-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0007_auto_20191031_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentifybehaviorhabits',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='useridentifyselftalkhabits',
            name='current_reality',
        ),
    ]
