# Generated by Django 2.1 on 2019-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0008_auto_20191031_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='effect',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='effect',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Effect'),
        ),
    ]
