# Generated by Django 2.1 on 2019-11-22 05:03

from django.db import migrations, models
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0009_auto_20191031_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('cr_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Current Reality Instruction Video Link')),
                ('isth_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Self-talk Instruction Video Link')),
                ('ibh_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Behavior Instruction Video Link')),
                ('ihyli_instruction_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Habitats Instruction Video Link')),
            ],
            options={
                'verbose_name_plural': 'Instruction Videos',
                'verbose_name': 'Instruction Video',
            },
        ),
        migrations.RemoveField(
            model_name='currentreality',
            name='cr_instruction_video',
        ),
        migrations.RemoveField(
            model_name='currentreality',
            name='ibh_instruction_video',
        ),
        migrations.RemoveField(
            model_name='currentreality',
            name='ihyli_instruction_video',
        ),
        migrations.RemoveField(
            model_name='currentreality',
            name='isth_instruction_video',
        ),
    ]
