# Generated by Django 2.1 on 2019-11-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0010_auto_20191122_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionvideos',
            options={'verbose_name': 'Instruction Videos', 'verbose_name_plural': 'Instruction Videos'},
        ),
    ]
