# Generated by Django 2.1 on 2019-12-11 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0011_auto_20191122_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='behavior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ibh_behavior', to='causalforces.Behavior'),
        ),
    ]
