# Generated by Django 2.1 on 2019-12-27 05:27

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0012_auto_20191211_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Money Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_money_effects', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Money Effect on Life',
                'verbose_name_plural': 'Money Effects on Life',
            },
        ),
        migrations.CreateModel(
            name='PeopleEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='People Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_people_effects', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'People Effect on Life',
                'verbose_name_plural': 'People Effects on Life',
            },
        ),
        migrations.CreateModel(
            name='SelfEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Self Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_self_effects', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Self Effect on Life',
                'verbose_name_plural': 'Self Effects on Life',
            },
        ),
    ]
