# Generated by Django 2.1 on 2019-12-27 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causalforces', '0013_moneyeffect_peopleeffect_selfeffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_effects_cr', to='causalforces.CurrentReality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='behavior',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_current_reality', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='believe',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_reality_believe', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='contentofselftalk',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_reality_content_of_self_talk', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='moneyeffect',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_money_effects', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='peopleeffect',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_people_effects', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='selfeffect',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_self_effects', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_current_reality', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='userbelieve',
            name='believe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='believe_user_believes', to='causalforces.Believe'),
        ),
        migrations.AlterField(
            model_name='userbelieve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_believes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='behavior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ibh_behavior', to='causalforces.Behavior'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ibh_thought', to='causalforces.Thought'),
        ),
        migrations.AlterField(
            model_name='useridentifybehaviorhabits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ibh_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ihyli_cr', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='useridentifyhabitatsyoulivein',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ihyli_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='content_of_self_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identify_self_talk_habits_cst', to='causalforces.ContentOfSelfTalk'),
        ),
        migrations.AlterField(
            model_name='useridentifyselftalkhabits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identify_self_talk_habits_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usereffects',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_money_effect', to='causalforces.MoneyEffect'),
        ),
        migrations.AddField(
            model_name='usereffects',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_people_effect', to='causalforces.PeopleEffect'),
        ),
        migrations.AddField(
            model_name='usereffects',
            name='self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_self_effect', to='causalforces.SelfEffect'),
        ),
        migrations.AddField(
            model_name='usereffects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_effects', to=settings.AUTH_USER_MODEL),
        ),
    ]
