# Generated by Django 2.1 on 2020-01-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causalforces', '0014_auto_20191227_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementBelieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Movement Believe')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_movement_believe', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Movement Believe',
                'verbose_name_plural': 'Movement Believes',
            },
        ),
        migrations.CreateModel(
            name='NutritionBelieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Nutrition Believe')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_nutrition_believe', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Nutrition Believe',
                'verbose_name_plural': 'Nutrition Believes',
            },
        ),
        migrations.CreateModel(
            name='RestBelieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=200, verbose_name='Rest Believe')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_rest_believe', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Rest Believe',
                'verbose_name_plural': 'Rest Believes',
            },
        ),
        migrations.CreateModel(
            name='UserBelieves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_believes_cr', to='causalforces.CurrentReality')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_movement_believe', to='causalforces.MovementBelieve')),
                ('nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nutrition_believe', to='causalforces.NutritionBelieve')),
                ('rest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rest_believe', to='causalforces.RestBelieve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_movement_believe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='believe',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='userbelieve',
            name='believe',
        ),
        migrations.RemoveField(
            model_name='userbelieve',
            name='user',
        ),
        migrations.DeleteModel(
            name='Believe',
        ),
        migrations.DeleteModel(
            name='UserBelieve',
        ),
    ]
