# Generated by Django 2.1 on 2020-01-13 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causalforces', '0015_auto_20200103_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorHighIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Behavior High Intensity',
                'verbose_name_plural': 'Behavior High Intensity',
            },
        ),
        migrations.CreateModel(
            name='BehaviorLowIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Behavior Low Intensity',
                'verbose_name_plural': 'Behavior Low Intensity',
            },
        ),
        migrations.CreateModel(
            name='BehaviorMediumIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Behavior Medium Intensity',
                'verbose_name_plural': 'Behavior Medium Intensity',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=250, verbose_name='Habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='ThoughtHighIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Thought High Intensity',
                'verbose_name_plural': 'Thought High Intensity',
            },
        ),
        migrations.CreateModel(
            name='ThoughtLowIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Thought Low Intensity',
                'verbose_name_plural': 'Thought Low Intensity',
            },
        ),
        migrations.CreateModel(
            name='ThoughtMediumIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('self', models.CharField(max_length=250, verbose_name='Thought')),
                ('people', models.CharField(max_length=250, verbose_name='Intent')),
                ('money', models.CharField(max_length=250, verbose_name='Biology')),
            ],
            options={
                'verbose_name': 'Thought Medium Intensity',
                'verbose_name_plural': 'Thought Medium Intensity',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('intensity', models.CharField(max_length=50, verbose_name='Intensity')),
                ('how_long', models.CharField(max_length=60, verbose_name='How Long Each Time?')),
                ('times_a_day', models.CharField(max_length=60, verbose_name='Times a Day')),
                ('looking_to', models.CharField(max_length=100, verbose_name='Who are You Looking to')),
                ('is_this_good_time', models.CharField(max_length=100, verbose_name='Is This Good Time to Talk to Them?')),
                ('after', models.CharField(max_length=50, verbose_name='After')),
                ('during', models.CharField(max_length=50, verbose_name='During')),
                ('Before', models.CharField(max_length=50, verbose_name='before')),
                ('polarity', models.CharField(max_length=50, verbose_name='Polarity')),
                ('emotion', models.CharField(max_length=50, verbose_name='Emotion')),
                ('function', models.CharField(max_length=50, verbose_name='Function')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('mindful_clear_ability', models.IntegerField(default=0, verbose_name='Mindful Clear Ability')),
                ('mindless_static_ignorance', models.IntegerField(default=0, verbose_name='Mindless Static Ignorance')),
                ('act_flow', models.IntegerField(default=0, verbose_name='Flow of Desire to Act')),
                ('act_lack', models.IntegerField(default=0, verbose_name='Lack of Desire to Act')),
                ('cared_for', models.CharField(max_length=50, verbose_name='Is this place Cared for?')),
                ('am_i_appreciating', models.CharField(max_length=50, verbose_name='Am I Appreciating this Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserThought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('intensity', models.CharField(max_length=50, verbose_name='Intensity')),
                ('how_long', models.CharField(max_length=60, verbose_name='How Long Each Time?')),
                ('times_a_day', models.CharField(max_length=60, verbose_name='Times a Day')),
                ('looking_to', models.CharField(max_length=100, verbose_name='Who are You Looking to')),
                ('is_this_good_time', models.CharField(max_length=100, verbose_name='Is This Good Time to Talk to Them?')),
                ('after', models.CharField(max_length=50, verbose_name='After')),
                ('during', models.CharField(max_length=50, verbose_name='During')),
                ('before', models.CharField(max_length=50, verbose_name='Before')),
                ('polarity', models.CharField(max_length=50, verbose_name='Polarity')),
                ('emotion', models.CharField(max_length=50, verbose_name='Emotion')),
                ('function', models.CharField(max_length=50, verbose_name='Function')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contentofselftalk',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='useridentifybehaviorhabits',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='useridentifybehaviorhabits',
            name='thought',
        ),
        migrations.RemoveField(
            model_name='useridentifybehaviorhabits',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useridentifyhabitatsyoulivein',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='useridentifyhabitatsyoulivein',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useridentifyselftalkhabits',
            name='content_of_self_talk',
        ),
        migrations.RemoveField(
            model_name='useridentifyselftalkhabits',
            name='user',
        ),
        migrations.AddField(
            model_name='behavior',
            name='biology',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Biology'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='intent',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Intent'),
        ),
        migrations.AddField(
            model_name='thought',
            name='biology',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Biology'),
        ),
        migrations.AddField(
            model_name='thought',
            name='intent',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Intent'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_cr', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Behavior'),
        ),
        migrations.AlterField(
            model_name='currentreality',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_cr', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='currentreality',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategory_cr', to='categories.SubCategory'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_cr', to='causalforces.CurrentReality'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Thought'),
        ),
        migrations.DeleteModel(
            name='ContentOfSelfTalk',
        ),
        migrations.DeleteModel(
            name='UserIdentifyBehaviorHabits',
        ),
        migrations.DeleteModel(
            name='UserIdentifyHabitatsYouLiveIn',
        ),
        migrations.DeleteModel(
            name='UserIdentifySelfTalkHabits',
        ),
        migrations.AddField(
            model_name='userthought',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_thought', to='causalforces.Thought'),
        ),
        migrations.AddField(
            model_name='userthought',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_habit_cr', to='causalforces.CurrentReality'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to='causalforces.Habit'),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_behavior', to='causalforces.Behavior'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thoughtmediumintensity',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_medium_intensity', to='causalforces.Thought'),
        ),
        migrations.AddField(
            model_name='thoughtlowintensity',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_low_intensity', to='causalforces.Thought'),
        ),
        migrations.AddField(
            model_name='thoughthighintensity',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_high_intensity', to='causalforces.Thought'),
        ),
        migrations.AddField(
            model_name='habit',
            name='current_reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_cr', to='causalforces.CurrentReality'),
        ),
        migrations.AddField(
            model_name='behaviormediumintensity',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_medium_intensity', to='causalforces.Behavior'),
        ),
        migrations.AddField(
            model_name='behaviorlowintensity',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_low_intensity', to='causalforces.Behavior'),
        ),
        migrations.AddField(
            model_name='behaviorhighintensity',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_high_intensity', to='causalforces.Behavior'),
        ),
    ]
