# Generated by Django 2.1 on 2020-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0017_auto_20200113_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='high_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity::Self'),
        ),
        migrations.AddField(
            model_name='thought',
            name='low_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensit::Self'),
        ),
        migrations.AddField(
            model_name='thought',
            name='medium_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity::Self'),
        ),
    ]
