# Generated by Django 2.1 on 2020-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0018_auto_20200113_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorhighintensity',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='behaviorlowintensity',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='behaviormediumintensity',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='thoughthighintensity',
            name='thought',
        ),
        migrations.RemoveField(
            model_name='thoughtlowintensity',
            name='thought',
        ),
        migrations.RemoveField(
            model_name='thoughtmediumintensity',
            name='thought',
        ),
        migrations.AddField(
            model_name='behavior',
            name='high_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity Money'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='high_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity People'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='high_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity Self'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='low_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity Money'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='low_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity People'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='low_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity Self'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='medium_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity Money'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='medium_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity People'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='medium_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity Self'),
        ),
        migrations.AddField(
            model_name='thought',
            name='high_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity Money'),
        ),
        migrations.AddField(
            model_name='thought',
            name='high_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity People'),
        ),
        migrations.AddField(
            model_name='thought',
            name='low_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity Money'),
        ),
        migrations.AddField(
            model_name='thought',
            name='low_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity People'),
        ),
        migrations.AddField(
            model_name='thought',
            name='medium_intensity_money',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity Money'),
        ),
        migrations.AddField(
            model_name='thought',
            name='medium_intensity_people',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity People'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='high_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='High Intensity Self'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='low_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Low Intensity Self'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='medium_intensity_self',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Medium Intensity Self'),
        ),
        migrations.DeleteModel(
            name='BehaviorHighIntensity',
        ),
        migrations.DeleteModel(
            name='BehaviorLowIntensity',
        ),
        migrations.DeleteModel(
            name='BehaviorMediumIntensity',
        ),
        migrations.DeleteModel(
            name='ThoughtHighIntensity',
        ),
        migrations.DeleteModel(
            name='ThoughtLowIntensity',
        ),
        migrations.DeleteModel(
            name='ThoughtMediumIntensity',
        ),
    ]
