# Generated by Django 2.1 on 2020-01-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causalforces', '0019_auto_20200113_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingMoneyEffect',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=255, verbose_name='Money Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_money_effect', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Living Money Effects on Life',
                'verbose_name': 'Living Money Effect on Life',
            },
        ),
        migrations.CreateModel(
            name='LivingMovement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(
                    max_length=255, verbose_name='Movement Living')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_movement', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Movement Livings',
                'verbose_name': 'Movement Living',
            },
        ),
        migrations.CreateModel(
            name='LivingNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=255,
                                          verbose_name='Nutrition Living')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_nutrition', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Nutrition Livings',
                'verbose_name': 'Nutrition Living',
            },
        ),
        migrations.CreateModel(
            name='LivingPeopleEffect',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=255, verbose_name='People Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_people_effect', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Living People Effects on Life',
                'verbose_name': 'Living People Effect on Life',
            },
        ),
        migrations.CreateModel(
            name='LivingRest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=255, verbose_name='Rest Living')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_rest', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Rest Livings',
                'verbose_name': 'Rest Living',
            },
        ),
        migrations.CreateModel(
            name='LivingSelfEffect',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=255, verbose_name='Self Effect')),
                ('order', models.IntegerField(default=0)),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='cr_living_self_effect', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name_plural': 'Living Self Effects on Life',
                'verbose_name': 'Living Self Effect on Life',
            },
        ),
        migrations.CreateModel(
            name='UserCR',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(
                    default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(
                    auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(
                    auto_now=True, verbose_name='changed at')),
                ('mindful_ability', models.IntegerField(blank=True,
                                                        default=0, null=True, verbose_name='Mindful Clear Ability')),
                ('mindless_ignorance', models.IntegerField(
                    blank=True, default=0, null=True, verbose_name='Mindless Static Ignorance')),
                ('act_flow', models.IntegerField(blank=True, default=0,
                                                 null=True, verbose_name='Flow of Desire to Act')),
                ('act_lack', models.IntegerField(blank=True, default=0,
                                                 null=True, verbose_name='Lack of Desire to Act')),
                ('cared_for', models.CharField(blank=True, max_length=50,
                                               null=True, verbose_name='Is this place Cared for?')),
                ('am_i_appreciating', models.CharField(blank=True, max_length=50,
                                                       null=True, verbose_name='Am I Appreciating this Place')),
                ('current_reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='user_cr_cr_fk', to='causalforces.CurrentReality')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='user_habit', to='causalforces.Habit')),
                ('living_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='user_living_money_effect', to='causalforces.LivingMoneyEffect')),
                ('living_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='user_movement_living', to='causalforces.LivingMovement')),
                ('living_nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='user_nutrition_living', to='causalforces.LivingNutrition')),
                ('living_people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='user_living_people_effect', to='causalforces.LivingPeopleEffect')),
                ('living_rest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='user_rest_living', to='causalforces.LivingRest')),
                ('living_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='user_living_self_effect', to='causalforces.LivingSelfEffect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userbelieves',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='userbelieves',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='userbelieves',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='userbelieves',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='userbelieves',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usereffects',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='usereffects',
            name='money',
        ),
        migrations.RemoveField(
            model_name='usereffects',
            name='people',
        ),
        migrations.RemoveField(
            model_name='usereffects',
            name='self',
        ),
        migrations.RemoveField(
            model_name='usereffects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='Before',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='looking_to',
        ),
        migrations.RemoveField(
            model_name='userthought',
            name='looking_to',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='before',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Before'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='talking_to',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Who Are You Talking to in this Thought'),
        ),
        migrations.AddField(
            model_name='userthought',
            name='talking_to',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Who Are You Talking to in this Thought'),
        ),
        migrations.AlterField(
            model_name='moneyeffect',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Money Effect'),
        ),
        migrations.AlterField(
            model_name='movementbelieve',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Movement Believe'),
        ),
        migrations.AlterField(
            model_name='nutritionbelieve',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Nutrition Believe'),
        ),
        migrations.AlterField(
            model_name='peopleeffect',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='People Effect'),
        ),
        migrations.AlterField(
            model_name='restbelieve',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Rest Believe'),
        ),
        migrations.AlterField(
            model_name='selfeffect',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Self Effect'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='after',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='After'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='during',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='During'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='emotion',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='function',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='how_long',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='How Long Each Time?'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='intensity',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Intensity'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='is_this_good_time',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Is This Good Time to Talk to Them?'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='polarity',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='times_a_day',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='Times a Day'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='after',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='After'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='before',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Before'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='during',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='During'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='emotion',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='function',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='how_long',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='How Long Each Time?'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='intensity',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Intensity'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='is_this_good_time',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Is This Good Time to Talk to Them?'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='polarity',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='userthought',
            name='times_a_day',
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name='Times a Day'),
        ),
        migrations.DeleteModel(
            name='UserBelieves',
        ),
        migrations.DeleteModel(
            name='UserEffects',
        ),
        migrations.DeleteModel(
            name='UserHabit',
        ),
        migrations.AddField(
            model_name='usercr',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_money_effect', to='causalforces.MoneyEffect'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_movement_believe', to='causalforces.MovementBelieve'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_nutrition_believe', to='causalforces.NutritionBelieve'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_people_effect', to='causalforces.PeopleEffect'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='rest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_rest_believe', to='causalforces.RestBelieve'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_self_effect', to='causalforces.SelfEffect'),
        ),
        migrations.AddField(
            model_name='usercr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_cr_user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
