# Generated by Django 2.1 on 2020-02-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0021_auto_20200131_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructionvideos',
            old_name='ihyli_instruction_video',
            new_name='habitats_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='cr_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='ibh_instruction_video',
        ),
        migrations.RemoveField(
            model_name='instructionvideos',
            name='isth_instruction_video',
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='body_ability_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Body Ability Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='deeper_behavior_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Deeper into this Behavior Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='deeper_thought_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Deeper into this Thought Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='fundamentals_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='3 Fundamentals to Optimize Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='imbh_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mindless Behavior Habit Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='imsth_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mindless Self-Talk Habit Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='measure_bsth_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Measure Behavior Self-Talk Habit Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='measure_sth_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Measure Self-Talk Habit Instruction Video Link'),
        ),
        migrations.AddField(
            model_name='instructionvideos',
            name='negative_instruction_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='A NEGATIVE Instruction Video Link'),
        ),
    ]
