# Generated by Django 2.1 on 2020-02-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0022_auto_20200210_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentreality',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cr', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='currentreality',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_cr', to='categories.SubCategory'),
        ),
    ]
