# Generated by Django 2.1 on 2020-03-02 06:26

from django.db import migrations, models
import django.db.models.deletion
import iow.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0023_auto_20200217_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=250, verbose_name='Life')),
                ('current_reality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_cr', to='causalforces.CurrentReality')),
            ],
            options={
                'verbose_name': 'Life',
                'verbose_name_plural': 'Lifes',
            },
        ),
        migrations.CreateModel(
            name='ULife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=250, verbose_name='Life')),
                ('current_thought', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_thought', to='causalforces.Thought')),
            ],
            options={
                'verbose_name': 'ULife',
                'verbose_name_plural': 'ULifes',
            },
        ),
        migrations.CreateModel(
            name='UserLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=iow.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('thought', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_life', to='causalforces.Thought')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
