# Generated by Django 2.1 on 2020-03-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0024_life_ulife_userlife'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='life',
            name='current_reality',
        ),
        migrations.RemoveField(
            model_name='ulife',
            name='current_thought',
        ),
        migrations.RemoveField(
            model_name='userlife',
            name='thought',
        ),
        migrations.DeleteModel(
            name='Life',
        ),
        migrations.DeleteModel(
            name='ULife',
        ),
        migrations.DeleteModel(
            name='UserLife',
        ),
    ]
