# Generated by Django 2.1 on 2020-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0027_auto_20200302_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorlife',
            name='name',
            field=models.CharField(max_length=250, verbose_name='BehaviorLife'),
        ),
    ]
