# Generated by Django 2.1 on 2020-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0028_auto_20200302_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='behaviorlife',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Times a Day'),
        ),
        migrations.AddField(
            model_name='userthought',
            name='life',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Life'),
        ),
    ]
