# Generated by Django 2.1 on 2020-03-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0031_auto_20200303_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthought',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_life', to='causalforces.Life'),
        ),
    ]
