# Generated by Django 2.1 on 2020-03-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0032_auto_20200303_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='behaviorlife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbehavior_life', to='causalforces.Life'),
        ),
    ]
