# Generated by Django 2.1 on 2020-03-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0033_auto_20200303_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehavior',
            name='behaviorlife',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviorlife', to='causalforces.Life'),
        ),
    ]
