# Generated by Django 2.1 on 2020-03-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0036_auto_20200305_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfe',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Self'),
        ),
    ]
