# Generated by Django 2.1 on 2020-03-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0043_behaviormoney'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name': 'Money', 'verbose_name_plural': 'Moneys'},
        ),
    ]
