# Generated by Django 2.1 on 2020-03-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0044_auto_20200306_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behaviormoney',
            options={'verbose_name': 'BehaviorMoney', 'verbose_name_plural': 'BehaviorMoneys'},
        ),
    ]
