# Generated by Django 2.1 on 2020-03-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0045_auto_20200306_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='behaviormoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviormoney', to='causalforces.BehaviorMoney'),
        ),
    ]
