# Generated by Django 2.1 on 2020-03-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190919_1853'),
        ('causalforces', '0047_auto_20200309_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentReality',
            new_name='Current_Reality',
        ),
    ]
