# Generated by Django 2.1 on 2020-03-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0051_auto_20200220_1323'),
        ('causalforces', '0049_auto_20200309_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_reality',
            name='want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_cr', to='causeandeffects.Want'),
        ),
    ]
