# Generated by Django 2.1 on 2020-03-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causeandeffects', '0051_auto_20200220_1323'),
        ('causalforces', '0050_current_reality_want'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_reality',
            name='want',
        ),
        migrations.AddField(
            model_name='current_reality',
            name='related_want',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_want_fk', to='causeandeffects.Want'),
        ),
    ]
