# Generated by Django 2.1 on 2020-03-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causalforces', '0051_auto_20200310_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forthlevelcontent',
            name='third_level',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s1_l3_button1_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s1_l3_button2_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s1_l3_button3_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s2_l3_button1_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s2_l3_button2_text',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='negative_i_want_s2_l3_button3_text',
        ),
        migrations.DeleteModel(
            name='ForthLevelContent',
        ),
    ]
